#!/bin/bash
#
# Builds the libsxg deb packages. The script must be run at the root
# directory of the libsxg source tree. The deb packages will be copied to
# the current directory.
#
# This script is written mainly for CI.

set -ex

readonly SRCDIR="${PWD}"
readonly DESTDIR="${PWD}/output"
readonly REPOSITORY="$1"
readonly WORKDIR="$(mktemp -d --tmpdir build_deb.XXXXXX)"
readonly NAME='libsxg'
readonly VERSION='0.2'
readonly TARNAME="${NAME}_${VERSION}"

rm "${destdir}/*" -rf
echo "Working in ${WORKDIR}"

cd "${WORKDIR}"
git clone -b master "${REPOSITORY}" libsxg-repo
cp -r ${SRCDIR}/debian libsxg-repo
cd libsxg-repo
git archive --format=tar.gz --output="${WORKDIR}/${TARNAME}.orig.tar.gz" \
    --prefix="${NAME}/" HEAD
rm .git -rf

debuild -b
dpkg-buildpackage

mkdir -p "${DESTDIR}"
cp -r ../* "${DESTDIR}"
rm -r "${DESTDIR}/libsxg-repo"
cd ..
lintian -viI --pedantic ${NAME}_${VERSION}-1_amd64.changes
cd ..

echo "Full package built in ${WORKDIR}"
#rm -rf "${WORKDIR}"
