#!/bin/bash
#
# Builds the libsxg deb packages for multiple debian family OS with Docker.
# This script must be run at the root directory of the libsxg source tree.
# Generated deb packages will put in the directory with the same name of
# Dockerfiles.

set -ex

readonly REPOSITORY="$1"
readonly DEB_DOCKER="dockerfiles/deb.dockerfile"
readonly DISTROS=(
  ubuntu:bionic
  debian:buster-slim
  ubuntu:disco
)

rm -rf ./libsxg
cp -r "${REPOSITORY}" ./libsxg

for distro in ${DISTROS[@]}; do
  echo "Target: ${distro}"

  image_tag="${distro}-libsxg"
  docker build --build-arg base_image=${distro} --build-arg repository=./libsxg -t "${image_tag}" -f "${DEB_DOCKER}" .
  dirname=`echo "${distro}" | cut -f 2 -d':'`
  echo "Dirname: ${dirname}"
  mkdir -p "${dirname}"
  docker run --rm \
    --mount "type=bind,source=${PWD}/${dirname},target=/packaging/output" \
    "${image_tag}"
  echo "Wrote deb file in ${distro}."
done
rm -rf ./libsxg
