require "bundler/gem_tasks"
require "rake/testtask"
require "rake/extensiontask"

Rake::TestTask.new(:test) do |t|
  t.libs << "test"
  t.libs << "lib"
  t.test_files = FileList["test/**/*_test.rb"]
end

Rake::ExtensionTask.new("sxg") do |ext|
  ext.ext_dir = "ext/sxg"
  ext.lib_dir = "lib/sxg"
  ext.extra_options << '-lsxg'
 end

task :default => :test
