#!/bin/bash
#
# Builds the libsxg deb packages. The script must be run at the root
# directory of the libsxg source tree. The deb packages will be copied to
# the current directory.
#
# This script is written mainly for CI.

set -ex

readonly SRCDIR="${PWD}"
readonly TARGET_DIR="${1}"
readonly WORKDIR="$(mktemp -d --tmpdir=/tmp build_deb.XXXXXX)"
readonly NAME='libsxg'
readonly VERSION='0.1'
readonly TARNAME="${NAME}_${VERSION}"
readonly TARGET_NAME='libsxg-dev'
readonly ARCH="$(dpkg --print-architecture)"
readonly RELEASE="$(lsb_release -cs)"

echo "Working in ${WORKDIR}"

git archive --format=tar.gz --output="${WORKDIR}/${TARNAME}.orig.tar.gz" \
    --prefix="${NAME}/" HEAD
cd "${WORKDIR}"
tar xf "${TARNAME}.orig.tar.gz"
cd "${NAME}"
ln -s packaging/debian .

debuild -uc -us -b

cp ../*.deb \
   "${SRCDIR}/${TARGET_DIR}/${TARGET_NAME}_${VERSION}_${ARCH}_${RELEASE}.deb"

rm -rf "${WORKDIR}"
