#!/bin/bash
#
# Builds the libsxg deb packages for multiple debian family OS with Docker.
# This script must be run at the root directory of the libsxg source tree.
# Generated deb packages will put in the directory with the same name of
# Dockerfiles.

set -ex
readonly DEB_DOCKER="packaging/dockerfiles/deb.dockerfile"
readonly DISTROS=(
  debian:buster-slim
  debian:stretch-slim
  ubuntu:disco
  ubuntu:bionic
)

for distro in ${DISTROS[@]}; do
  echo "Target: ${distro}"
  image_tag="${distro}-libsxg"
  docker build --build-arg base_image=${distro} -t "${image_tag}" -f "${DEB_DOCKER}" .
  mkdir -p "${distro}"
  docker run --rm \
    --mount "type=bind,source=${PWD}/${distro},target=/libsxg/docker_output" \
    "${image_tag}"
  echo "Wrote deb file in ${distro}."
done
